name: Publish .NET Release

# 触发方式：手动触发和推送到master分支时触发
on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ "master" ]
    # 可选：仅当特定文件变更时触发
    # paths:
    #   - 'src/**'
    #   - '*.csproj'

permissions:
  contents: write  # 需要写入权限来创建Release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
    
    - name: Get version from project
      id: get_version
      run: |
          TargetVersion=""
          # 如果是 Release 触发，使用 Release 标签作为版本号
          if [ "${{ github.event.release.tag_name }}" ] ; then
            TargetVersion=${{ github.event.release.tag_name }}
          else
            # 否则从项目文件中提取版本号（根据实际情况调整路径）
            TargetVersion=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./FailReport.csproj)
          fi
          # 移除可能的前缀 'v'
          TargetVersion=${TargetVersion#v}
          echo "TargetVersion: $TargetVersion"
          echo "TargetVersion=$TargetVersion" >> $GITHUB_OUTPUT
    
    - name: Zip publish artifacts
      run: |
        cd ./publish
        zip -r ../release-artifacts.zip ./*
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body: |
          ## Release v${{ steps.get_version.outputs.version }}
          Automated release generated by GitHub Actions.
        files: ./release-artifacts.zip
        draft: false
        prerelease: false
