name: Publish Docker Image

on:
  push:
    paths:
      - 'FailReport.csproj'
  workflow_dispatch:
    inputs:
      autoWithLatestTag:
        description: '自动添加 Latest 标签'
        required: true
        default: true
        type: boolean
  release:
    types: [created]

env:
  # DockerHub 仓库信息
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKER_IMG_NAME: "adminpc/failreport"
  
  # GHCR 仓库信息
  GHCR_USERNAME: ${{ github.repository_owner }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GHC_IMG_NAME: "ghcr.io/${{ github.repository_owner }}/failreport"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # 关键：添加GHCR推送所需的权限
    permissions:
      contents: read  # 读取代码权限
      packages: write  # 推送镜像到GHCR的权限
      
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取目标版本号
        id: getTargetVersion
        run: |
          TargetVersion=""
          if [ "${{ github.event.release.tag_name }}" ] ; then
            TargetVersion=${{ github.event.release.tag_name }}
          else
            # 从项目文件提取版本号（确保路径正确）
            TargetVersion=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./FailReport.csproj)
          fi
          TargetVersion=${TargetVersion#v}  # 移除可能的前缀v
          echo "TargetVersion: $TargetVersion"
          echo "TargetVersion=$TargetVersion" >> $GITHUB_OUTPUT

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: 登录到 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PASSWORD }}

      - name: 生成镜像标签
        id: tags
        run: |
          targetVersion="${{ steps.getTargetVersion.outputs.TargetVersion }}"          
          # 版本化标签
          dockerTagWithVersion="${{ env.DOCKER_IMG_NAME }}:$targetVersion"
          ghcrTagWithVersion="${{ env.GHC_IMG_NAME }}:$targetVersion"
          
          # Latest 标签
          dockerTagWithLatest=""
          ghcrTagWithLatest=""
          # 修复条件判断（避免空值导致的语法错误）
          if [ "${{ github.event.inputs.autoWithLatestTag }}" = "true" ] || [ -n "${{ github.event.release.created_at || '' }}" ]; then
            dockerTagWithLatest="${{ env.DOCKER_IMG_NAME }}:latest"
            ghcrTagWithLatest="${{ env.GHC_IMG_NAME }}:latest"
          fi
          
          echo "dockerTagWithVersion=$dockerTagWithVersion" >> $GITHUB_OUTPUT
          echo "ghcrTagWithVersion=$ghcrTagWithVersion" >> $GITHUB_OUTPUT
          echo "dockerTagWithLatest=$dockerTagWithLatest" >> $GITHUB_OUTPUT
          echo "ghcrTagWithLatest=$ghcrTagWithLatest" >> $GITHUB_OUTPUT

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # 确认Dockerfile在根目录
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags.outputs.dockerTagWithVersion }}
            ${{ steps.tags.outputs.ghcrTagWithVersion }}
            ${{ steps.tags.outputs.dockerTagWithLatest }}
            ${{ steps.tags.outputs.ghcrTagWithLatest }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
