name: Publish .NET Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --self-contained false
    
    - name: Get version from project
      id: get_version
      run: |
          TargetVersion=""
          if [ "${{ github.event.release.tag_name }}" ] ; then
            TargetVersion=${{ github.event.release.tag_name }}
          else
            # 提取版本号（确保项目文件路径正确）
            TargetVersion=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./FailReport.csproj)
          fi
          TargetVersion=${TargetVersion#v}
          echo "TargetVersion: $TargetVersion"
          echo "TargetVersion=$TargetVersion" >> $GITHUB_OUTPUT
    
    - name: Zip publish artifacts (命名为项目名+版本号)
      id: zip_artifacts  # 添加id，用于后续引用
      run: |
        PROJECT_NAME="FailReport"
        # 修正变量引用语法
        ZIP_NAME="${PROJECT_NAME}_v${{ steps.get_version.outputs.TargetVersion }}.zip"
        zip -r "$ZIP_NAME" ./publish/*
        # 输出压缩包名称到步骤变量
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.TargetVersion }}
        name: Release v${{ steps.get_version.outputs.TargetVersion }}
        body: |
          ## Release v${{ steps.get_version.outputs.TargetVersion }}
          Automated release generated by GitHub Actions.
        # 通过步骤id和输出变量引用压缩包名称
        files: ./${{ steps.zip_artifacts.outputs.ZIP_NAME }}
        draft: false
        prerelease: false